name: Project video
on:
  push:
    branches:
      - master
jobs:
  create-video:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Research Project Action
        uses: Jonas-D-M/Research-Project@e70b182d6851df911ce530a11685209b31d06629
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          project-dir: .
