name: Project video
on:
  push:
    branches:
      - master

jobs:
  create-video:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: install ffmpeg
        run: |
          sudo apt-get install --no-upgrade ffmpeg -qq
      - name: install pm2
        run: npm install pm2 --save
      - name: install pm2 typescript
        run: pm2 install typescript
      - name: get ffmpeg  path
        id: get-ffmpeg-path
        run: echo "::set-output name=ffmpeg::$(which ffmpeg)"
      - name: get chrome path
        id: get-chrome-path
        run: echo "::set-output name=chrome::$(which google-chrome-stable)"
      - name: test the github action
        uses: jonas-d-m/research-project@v1.1.6
        with:
          ffmpeg-path: ${{ steps.get-ffmpeg-path.outputs.ffmpeg}}
          chrome-path: ${{steps.get-chrome-path.outputs.chrome}}
